# Generated by Django 4.1.4 on 2022-12-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_rename_creator_advertisement_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='user',
            new_name='creator',
        ),
    ]
